-- MySQL Script generated by MySQL Workbench
-- Sun Sep  9 15:18:23 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`User` (
  `id` INT NOT NULL,
  `username` VARCHAR(45) NULL,
  `password` VARCHAR(450) NULL,
  `is_deleted` VARCHAR(1) NOT NULL,
  `first_name` VARCHAR(50) NOT NULL,
  `last_name` VARCHAR(50) NOT NULL,
  `address1` VARCHAR(120) NOT NULL,
  `address2` VARCHAR(120) NULL,
  `city` VARCHAR(45) NOT NULL,
  `state` VARCHAR(2) NOT NULL,
  `postalcode` VARCHAR(16) NOT NULL,
  `lat` DECIMAL(9,6) NULL,
  `lon` DECIMAL(9,6) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Schedule`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Schedule` (
  `id` INT NOT NULL,
  `start_time` DATETIME NOT NULL,
  `end_time` DATETIME NOT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`id`, `user_id`),
  INDEX `fk_Schedule_User1_idx` (`user_id` ASC),
  CONSTRAINT `fk_Schedule_User1`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`User` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Location`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Location` (
  `id` INT NOT NULL,
  `Name` VARCHAR(250) NOT NULL,
  `address1` VARCHAR(120) NOT NULL,
  `address2` VARCHAR(120) NULL,
  `city` VARCHAR(45) NOT NULL,
  `state` VARCHAR(2) NULL,
  `lat` DECIMAL(9,6) NOT NULL,
  `lon` DECIMAL(9,6) NOT NULL,
  `postalcode` VARCHAR(16) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`LessonDao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Lesson` (
  `id` INT NOT NULL,
  `start_time` DATETIME NOT NULL,
  `end_time` DATETIME NOT NULL,
  `location_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_Lesson_Location1`
    FOREIGN KEY (`location_id`)
    REFERENCES `mydb`.`Location` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Notification`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Notification` (
  `id` INT NOT NULL,
  `message` VARCHAR(45) NOT NULL,
  `isRead` VARCHAR(1) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`User_Notification`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`User_Notification` (
  `notification_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`notification_id`, `user_id`),
  INDEX `fk_User_Notification_User1_idx` (`user_id` ASC),
  CONSTRAINT `fk_User_Notification_Notification1`
    FOREIGN KEY (`notification_id`)
    REFERENCES `mydb`.`Notification` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_User_Notification_User1`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`User` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Dance`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Dance` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(500) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`User_Dance`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`User_Dance` (
  `experience_years` INT NOT NULL,
  `learning_proficiency` INT NOT NULL,
  `user_id` INT NOT NULL,
  `dance_id` INT NOT NULL,
  PRIMARY KEY (`user_id`, `dance_id`),
  INDEX `fk_User_Dance_User1_idx` (`user_id` ASC),
  INDEX `fk_User_Dance_Dance1_idx` (`dance_id` ASC),
  CONSTRAINT `fk_User_Dance_User1`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`User` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_User_Dance_Dance1`
    FOREIGN KEY (`dance_id`)
    REFERENCES `mydb`.`Dance` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Role` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`User_Role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`User_Role` (
  `role_id` INT NULL,
  `user_id` INT NULL,
  PRIMARY KEY (`role_id`, `user_id`),
  INDEX `fk_User_Role_User1_idx` (`user_id` ASC),
  CONSTRAINT `fk_User_Role_Role1`
    FOREIGN KEY (`role_id`)
    REFERENCES `mydb`.`Role` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_User_Role_User1`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`User` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`User_Lesson`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`User_Lesson` (
  `user_id` INT NOT NULL,
  `lesson_id` INT NOT NULL,
  PRIMARY KEY (`user_id`, `lesson_id`),
  INDEX `fk_User_Lesson_Lesson1_idx` (`lesson_id` ASC),
  CONSTRAINT `fk_User_Lesson_User1`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`User` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_User_Lesson_Lesson1`
    FOREIGN KEY (`lesson_id`)
    REFERENCES `mydb`.`Lesson` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
