DELETE FROM DANCE;
DELETE FROM USER_ROLE;
DELETE FROM USER;
ALTER TABLE DANCE AUTO_INCREMENT = 1;
INSERT INTO DANCE VALUES(1, 'Waltz', 'elegant, classy');
INSERT INTO DANCE VALUES (2, 'Rumba', 'romantic, slow, easy');
INSERT INTO DANCE VALUES (3, 'Tango', 'romantic, staccato, dramatic');
ALTER TABLE USER AUTO_INCREMENT = 1;
INSERT INTO USER (username, password, is_deleted, first_name, last_name, address1, city, state, postalcode, pay_rate) VALUES ('mjackson', '123abc', 0, 'Michael', 'Jackson', '123 Main St', 'Madison', 'WI', '53705', 50.00);
INSERT INTO USER (username, password, is_deleted, first_name, last_name, address1, city, state, postalcode, pay_rate) VALUES ('mjessy', '123abc', 0, 'Mary', 'Jessy', '123 Main St', 'Madison', 'WI', '53704', 60.00);
ALTER TABLE ROLE AUTO_INCREMENT = 1;
INSERT INTO ROLE (name) VALUES ("instructor");
INSERT INTO ROLE (name) VALUES ("student");
INSERT INTO USER_ROLE (user_id, role_id) VALUES (1, 1);
INSERT INTO USER_ROLE (user_id, role_id) VALUES (2, 2);